dist: trusty
language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc libsdl2-dev libffi-dev python-dev -y
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - py.test --cov=CreatureRogue tests/
after_success:
  - coveralls