language: python
python:
  - "3.5"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose
  - pip install coverage
# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=CreatureRogue
after_success: coveralls